on:
  push:
    tags:
      - 'v*'

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: install microsoft fonts
        run: |
          echo 'ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true' | sudo debconf-set-selections
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ttf-mscorefonts-installer
          sudo fc-cache -f -v

      - name: install typst
        run: |
          snap install typst

      - name: Compile PDF
        run: |
          typst compile main.typ

      - name: Upload PDF
        uses: actions/upload-artifact@v7
        with:
          name: main.pdf
          path: main.pdf